name: Minify JavaScript

on:
  workflow_dispatch:
  push:
    branches:
      - timrichardson-patch-1  # Change this to your default branch
  pull_request:
    branches:
      - timrichardson-patch-1   # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify the Node.js version you want to use

    - name: Install Terser
      run: npm install --save-dev terser

    - name: Copy original JavaScript to dist
      run: mkdir -p dist && cp autocomplete.js dist/autocomplete.js

    - name: Minify JavaScript
      run: npx terser autocomplete.js -o dist/autocomplete.min.js --source-map "content=inline" --source-map "url=dist/autocomplete.min.js.map"
    
    - name: Upload original JavaScript
      uses: actions/upload-artifact@v3
      with:
        name: autocomplete.js
        path: dist/autocomplete.js
    
    - name: Upload minified JavaScript
      uses: actions/upload-artifact@v3
      with:
        name: autocomplete.min.js
        path: dist/autocomplete.min.js

    - name: Upload source map
      uses: actions/upload-artifact@v3
      with:
        name: autocomplete.min.js.map
        path: dist/autocomplete.min.js.map

