name: Minify JavaScript

on:
  push:
    branches:
      - tim-richardson-patch-1  # Change this to your default branch
  pull_request:
    branches:
      - tim-richardson-patch-1   # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify the Node.js version you want to use

    - name: Install Terser
      run: npm install --save-dev terser

    - name: Minify JavaScript
      run: npx terser autocomplete.js -o autocomplete.min.js

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: minified-js
        path: autocomplete.min.js
